<?php

namespace AgendaPedalBundle\Repository;

/**
 * AgendamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
