<?php

namespace AgendaPedalBundle\Repository;

/**
 * DistanciaPedalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistanciaPedalRepository extends \Doctrine\ORM\EntityRepository
{
}
