<?php

namespace AgendaPedalBundle\Repository;

/**
 * RitmoPedalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RitmoPedalRepository extends \Doctrine\ORM\EntityRepository
{
}
