<?php

namespace AgendaPedalBundle\Repository;

/**
 * TipoPedalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPedalRepository extends \Doctrine\ORM\EntityRepository
{
}
